import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import Menu from "../components/Sidebar";
import "./globals.css";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={quicksand.variable}>
      <body className="antialiased flex flex-col md:flex-row">
        <Menu />
        <main className="flex flex-col">{children}</main>
      </body>
    </html>
  );
}
